stages:
  transfer_to_sql_and_unificate_data:
    cmd: python3 ../stage_runner.py --job transfer_to_sql_and_unificate_data
    params:
    - transfer_to_sql_and_unificate_data
    deps:
    - ../src/collect_data/collect_data.py
    - ../crawler/divar_data_collection/apartment_tehran.csv
    - ../crawler/divar_data_collection/house_tehran.csv
    outs:
    - data/raw/