stages:
  transfer_to_sql_and_unificate_data:
    cmd: python3 ../stage_runner.py --job transfer_to_sql_and_unificate_data
    params:
    - transfer_to_sql_and_unificate_data
    deps:
    - ../src/collect_data/collect_data.py
    - ../crawler/divar_data_collection/apartment_tehran.csv
    - ../crawler/divar_data_collection/house_tehran.csv
    outs:
    - data/raw/

  split_data:
    cmd: python3 ../stage_runner.py --job split_data
    params:
      - split_data
    deps:
      - ../src/collect_data/split_data.py
      - data/raw/
    outs:
      - data/train_test/

  manual_feature_eng:
    cmd: python3 ../stage_runner.py --job manual_feature_eng
    params:
      - manual_feature_eng
    deps:
      - ../src/feature_eng/manual_features.py
      - data/train_test/
    outs:
      - data/train_test_manual/

  tf_idf_eng:
    cmd: python3 ../stage_runner.py --job tf_idf_eng
    params:
      - tf_idf_eng
    deps:
      - ../src/feature_eng/tfidf_features.py
      - data/train_test_manual/
    outs:
      - data/train_test_tf_idf/

  char_vect_eng:
    cmd: python3 ../stage_runner.py --job char_vect_eng
    params:
      - char_vect_eng
    deps:
      - ../src/feature_eng/char_vectorizer.py
      - data/train_test/
    outs:
      - data/train_test_char_vectorizer/

  bert_encoding:
    cmd: python3 ../stage_runner.py --job bert_encoding
    params:
      - bert_encoding
    deps:
      - ../src/feature_eng/bert_encoding.py
      - data/train_test_manual/
    outs:
      - data/train_test_bert_encoded/

  data_augmentation:
    cmd: python3 ../stage_runner.py --job data_augmentation
    params:
      - data_augmentation
    deps:
      - ../src/balance_data/data_augmentation.py
      - data/train_test_manual/
    outs:
      - data/train_test_augmentation/

  pca_logistic_regression:
    cmd: python3 ../stage_runner.py --job pca_logistic_regression
    params:
      - pca_logistic_regression
    deps:
      - ../src/pca_logistic_regression/pca_lr.py
      - data/train_test_char_vectorizer/
    metrics:
      - report/pca_logistic_regression.json:
          cache: false

  random_foreest:
    cmd: python3 ../stage_runner.py --job random_forest
    params:
      - random_forest
    deps:
      - ../src/tfidf_random_forest/random_forest.py
      - data/train_test_tf_idf/
    metrics:
      - report/tfidf_random_forest.json:
          cache: false

  autoencoder_logistic_regression:
    cmd: python3 ../stage_runner.py --job autoencoder_logistic_regression
    params:
      - autoencoder_logistic_regression
    deps:
      - ../src/autoencoder_logistic_regression/autoencoder_logistic_regression.py
      - data/train_test_tf_idf/
    metrics:
      - report/autoencoder_logistic_regression_class_weights.json:
          cache: false
