stages:
  transfer_to_sql_and_unificate_data:
    cmd: python ../stage_runner.py --job transfer_to_sql_and_unificate_data
    params:
    - transfer_to_sql_and_unificate_data
    deps:
    - ../src/collect_data/collect_data.py
    outs:
    - data/