transfer_to_sql_and_unificate_data:
  csv_path_list:
    - ../crawler/divar_data_collection/house_tehran.csv
    - ../crawler/divar_data_collection/apartment_tehran.csv
  file_directory: data/raw/

split_data:
  file_path: data/raw/posts.csv
  train_test_dir: data/train_test/

manual_feature_eng:
  train_test_dir: data/train_test/
  out_dir: data/train_test_manual/

tf_idf_eng:
  train_test_inp_dir: data/train_test_manual/
  out_dir: data/train_test_tf_idf/
  min_df: 5

random_forest:
  inp_dir: data/train_test_tf_idf/
  metric_path: report/tfidf_random_forest.json
  n_estimators: 100
  threshold: 0.5